eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
server:
  port: 8081
  

spring:
  application:
    name: WELCOME-API
  boot:
    admin:
      client:
        url: http://localhost:8090
  management:
    endpoints:
      web:
        exposure:
          include: '*'
 